# Generated by Django 2.1.4 on 2019-02-24 16:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('userregistration', '0002_auto_20190217_0941'),
    ]

    operations = [
        migrations.CreateModel(
            name='EN_Categories',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('retired', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userregistration.EN_Users')),
            ],
        ),
        migrations.CreateModel(
            name='EN_SubCategories',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('retired', models.BooleanField(default=False)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='categories.EN_Categories')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userregistration.EN_Users')),
            ],
        ),
    ]
