# Generated by Django 2.1.4 on 2019-02-17 04:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userregistration', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='EN_UserRegistration',
            new_name='EN_Users',
        ),
    ]
